/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airplanesystem;

import java.util.Random;
import javax.swing.JOptionPane;
import java.util.Calendar;

import java.util.Random;

import java.sql.Time;
import java.util.Calendar;
import javax.swing.plaf.metal.MetalBorders;

/**
 *
 * @author macbookair
 */
public class BookFlight extends javax.swing.JFrame {

    /**
     * Creates new form BookFlight
     */
    public BookFlight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fillPassportNumber = new javax.swing.JTextField();
        fillFname = new javax.swing.JTextField();
        fillLname = new javax.swing.JTextField();
        dayComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fromDestPicker = new javax.swing.JComboBox<>();
        toDestPicker = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        oneWayButton = new javax.swing.JRadioButton();
        roundTripButton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        dayReturnBox = new javax.swing.JComboBox<>();
        monthReturnBox = new javax.swing.JComboBox<>();
        yearReturnBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bookFlight = new javax.swing.JButton();
        priceButton = new javax.swing.JButton();
        pricelabel = new javax.swing.JLabel();
        economyBtn = new javax.swing.JRadioButton();
        businessBtn = new javax.swing.JRadioButton();
        firstclassBtn = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Krungthep", 0, 36)); // NOI18N
        jLabel1.setText("Destination Picker");

        jLabel2.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel2.setText("Passport No.");

        jLabel3.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel6.setText("Date of Return");

        jLabel7.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel7.setText("Select your class");

        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "22", "23", "24", "25", "26", "27", "28", "29" }));

        jLabel8.setFont(new java.awt.Font("Krungthep", 0, 36)); // NOI18N
        jLabel8.setText("Fill your details");

        jLabel9.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel9.setText("To");

        jLabel10.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel10.setText("From");

        fromDestPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skopje, MKD", "Podgorica, MNE", "Tivat, MNE", "Belgrade, SRB", "Novi Sad, SRB", "Tirana, ALB", "Prishtina, RKS", "Sarajevo, BIH", "Banja Luka, BIH", "Istanbul, TR", "Ankara, TR", "Stuttgart, DE", " " }));
        fromDestPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromDestPickerActionPerformed(evt);
            }
        });

        toDestPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skopje, MKD", "Podgorica, MNE", "Tivat, MNE", "Belgrade, SRB", "Novi Sad, SRB", "Tirana, ALB", "Prishtina, RKS", "Sarajevo, BIH", "Banja Luka, BIH", "Istanbul, TR", "Ankara, TR", "Stuttgart, DE", " " }));

        jLabel12.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel12.setText("One-way");

        jLabel13.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel13.setText("Round-trip");

        buttonGroup1.add(oneWayButton);
        oneWayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneWayButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(roundTripButton);
        roundTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTripButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabel11.setText("Date of Departure");

        dayReturnBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthReturnBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));

        yearReturnBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "22", "23", "24", "25", "26", "27", "28", "29" }));

        jLabel15.setFont(new java.awt.Font("Krungthep", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 102));
        jLabel15.setText("1 Handbag & 1 Checked Baggage are FREE");

        jLabel16.setFont(new java.awt.Font("Krungthep", 0, 36)); // NOI18N
        jLabel16.setText("Baggage Info");

        bookFlight.setBackground(new java.awt.Color(255, 0, 51));
        bookFlight.setText("BOOK FLIGHT");
        bookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightActionPerformed(evt);
            }
        });

        priceButton.setText("PRICE");
        priceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(economyBtn);
        economyBtn.setText("Economy");

        buttonGroup2.add(businessBtn);
        businessBtn.setText("Business");

        buttonGroup2.add(firstclassBtn);
        firstclassBtn.setText("First Class");

        jLabel19.setFont(new java.awt.Font("Krungthep", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 102));
        jLabel19.setText("any additional baggage will be paid by customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(241, 241, 241))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fillFname, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(fillLname, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(fillPassportNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayReturnBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthReturnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearReturnBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(economyBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(businessBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstclassBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(oneWayButton)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(roundTripButton)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fromDestPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toDestPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(107, 107, 107))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGap(165, 165, 165))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(priceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pricelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(bookFlight)
                            .addGap(29, 29, 29)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(145, 145, 145))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(826, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(434, 434, 434)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fillFname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fillLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(toDestPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fromDestPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fillPassportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(economyBtn)
                                    .addComponent(businessBtn)
                                    .addComponent(firstclassBtn))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(dayReturnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthReturnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearReturnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundTripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oneWayButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12)))))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bookFlight, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addComponent(pricelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(jLabel10)
                    .addContainerGap(341, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneWayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneWayButtonActionPerformed
        // TODO add your handling code here:
        
        if(oneWayButton.isSelected()){
            dayReturnBox.setEnabled(false);
            monthReturnBox.setEnabled(false);
            yearReturnBox.setEnabled(false);
            jLabel6.setEnabled(false);
        }
   
    }//GEN-LAST:event_oneWayButtonActionPerformed

    private void roundTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTripButtonActionPerformed
        // TODO add your handling code here:
        
         if(roundTripButton.isSelected()){
            dayReturnBox.setEnabled(true);
            monthReturnBox.setEnabled(true);
            yearReturnBox.setEnabled(true);
            jLabel6.setEnabled(true);
        }
    }//GEN-LAST:event_roundTripButtonActionPerformed

    private void fromDestPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromDestPickerActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_fromDestPickerActionPerformed

    private void bookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightActionPerformed
        // TODO add your handling code here:
       
        
       
        Ticket ticketpage = new Ticket();
        ticketpage.setVisible(true);
        Ticket.flightNumbe.setText(flightLetter() + flightNumber() + flightLetter());
        Ticket.gateBoarding.setText(gateNumber() + gateLetter());
        Ticket.seatBoarding.setText(seatPlace()+seatPlaceLetter());
        Ticket.boardinName.setText(fillFname.getText());
        Ticket.boardinglastname.setText(fillLname.getText());
        String destinationPicker = (String) fromDestPicker.getSelectedItem();
        Ticket.boardingFrom.setText(destinationPicker);
        String arrivePlace = (String) toDestPicker.getSelectedItem();
        Ticket.toBoarding.setText(arrivePlace);
        String dayB = (String) dayComboBox.getSelectedItem();
        String monthB = (String) monthComboBox.getSelectedItem();
        String yearB = (String) yearComboBox.getSelectedItem();
        Ticket.dateBoarding.setText(dayB + monthB + yearB);
        Ticket.nameSide.setText(fillFname.getText());
        Ticket.LNameSide.setText(fillLname.getText());
        Ticket.fromSide.setText(Ticket.boardingFrom.getText());
        Ticket.toSide.setText(Ticket.toBoarding.getText());
        Ticket.sideDate.setText(Ticket.dateBoarding.getText());
        Ticket.seatSide.setText(Ticket.seatBoarding.getText());
        Ticket.flightNumberSide.setText(Ticket.flightNumbe.getText());
        Ticket.gateSide.setText(Ticket.gateBoarding.getText());
        Ticket.boardingTime.setText(hours() + ":" + minutes());
       Ticket.boardingTimeSide.setText(Ticket.boardingTime.getText());
    
        
       
        
        
                
       
    }//GEN-LAST:event_bookFlightActionPerformed

    private void priceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceButtonActionPerformed
        // TODO add your handling code here:
            double economyclass;
            double businessclass;
            double firstclass;
            double flightfare = 150;
        if(economyBtn.isSelected() && oneWayButton.isSelected()){
            economyclass = 50;
            economyclass += flightfare;
           
            pricelabel.setText(String.valueOf(economyclass) + "€");
            JOptionPane.showMessageDialog(rootPane, "ATTENTION! \n IF YOU WISH TO PURCHASE THE TICKET FOR YOUR DESTINATION GO TO NEAREST POST OFFICE"
                    + " AND PURCHASE YOUR TICKET UNDER THE NAME OF INTERNATIONAL BALKAN AIRLINES CONFIRMATION CODE"
                    + "\n YOUR CONFIRMATION CODE WILL BE SAVED AS A FILE");
            writeToFile("CONFIRMATION CODE POST OFFICE:  " +flightNumber() + flightLetter() + flightNumber() + flightLetter() + flightLetter());
        }
        else if(businessBtn.isSelected() && oneWayButton.isSelected()){
            businessclass = 125;
            businessclass += flightfare;
            pricelabel.setText(String.valueOf(businessclass) + "€");
           JOptionPane.showMessageDialog(rootPane, "ATTENTION! \n IF YOU WISH TO PURCHASE THE TICKET FOR YOUR DESTINATION GO TO NEAREST POST OFFICE"
                    + " AND PURCHASE YOUR TICKET UNDER THE NAME OF INTERNATIONAL BALKAN AIRLINES CONFIRMATION CODE"
                    + "\n YOUR CONFIRMATION CODE WILL BE SAVED AS A FILE");
            writeToFile("CONFIRMATION CODE POST OFFICE:  " +flightNumber() + flightLetter() + flightNumber() + flightLetter() + flightLetter());
        }
        else if(firstclassBtn.isSelected() && oneWayButton.isSelected()){
            firstclass = 220;
            firstclass += flightfare;
            pricelabel.setText(String.valueOf(firstclass) + "€");
       JOptionPane.showMessageDialog(rootPane, "ATTENTION! \n IF YOU WISH TO PURCHASE THE TICKET FOR YOUR DESTINATION GO TO NEAREST POST OFFICE"
                    + " AND PURCHASE YOUR TICKET UNDER THE NAME OF INTERNATIONAL BALKAN AIRLINES CONFIRMATION CODE"
                    + "\n YOUR CONFIRMATION CODE WILL BE SAVED AS A FILE");
        writeToFile("CONFIRMATION CODE POST OFFICE:  " +flightNumber() + flightLetter() + flightNumber() + flightLetter() + flightLetter());
        }
        else if(economyBtn.isSelected() && roundTripButton.isSelected()){
            economyclass = 50;
            economyclass += flightfare * 1.5;
            pricelabel.setText(String.valueOf(economyclass) + "€");
            JOptionPane.showMessageDialog(rootPane, "ATTENTION! \n IF YOU WISH TO PURCHASE THE TICKET FOR YOUR DESTINATION GO TO NEAREST POST OFFICE"
                    + " AND PURCHASE YOUR TICKET UNDER THE NAME OF INTERNATIONAL BALKAN AIRLINES CONFIRMATION CODE"
                    + "\n YOUR CONFIRMATION CODE WILL BE SAVED AS A FILE");
             writeToFile("CONFIRMATION CODE POST OFFICE:  " +flightNumber() + flightLetter() + flightNumber() + flightLetter() + flightLetter());
        }
         else if(businessBtn.isSelected() && roundTripButton.isSelected()){
            businessclass = 125;
            businessclass += flightfare * 1.5;
            pricelabel.setText(String.valueOf(businessclass) + "€");
            JOptionPane.showMessageDialog(rootPane, "ATTENTION! \n IF YOU WISH TO PURCHASE THE TICKET FOR YOUR DESTINATION GO TO NEAREST POST OFFICE"
                    + " AND PURCHASE YOUR TICKET UNDER THE NAME OF INTERNATIONAL BALKAN AIRLINES CONFIRMATION CODE"
                    + "\n YOUR CONFIRMATION CODE WILL BE SAVED AS A FILE");
             writeToFile("CONFIRMATION CODE POST OFFICE:  " +flightNumber() + flightLetter() + flightNumber() + flightLetter() + flightLetter());
        }
         else if(firstclassBtn.isSelected() && roundTripButton.isSelected()){
            firstclass = 220;
            firstclass += flightfare * 1.5;
            pricelabel.setText(String.valueOf(firstclass) + "€");
            JOptionPane.showMessageDialog(rootPane, "ATTENTION! \n IF YOU WISH TO PURCHASE THE TICKET FOR YOUR DESTINATION GO TO NEAREST POST OFFICE"
                    + " AND PURCHASE YOUR TICKET UNDER THE NAME OF INTERNATIONAL BALKAN AIRLINES CONFIRMATION CODE"
                    + "\n YOUR CONFIRMATION CODE WILL BE SAVED AS A FILE");
             writeToFile("CONFIRMATION CODE POST OFFICE:  " +flightNumber() + flightLetter() + flightNumber() + flightLetter() + flightLetter());
        }
       
             
               
        
        
    }//GEN-LAST:event_priceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //ARRAY FOR GATE SEAT NUMBER
       
      
        
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    BookFlight frame = new BookFlight();
                    frame.setVisible(true);
                } catch(Exception e){
                    e.printStackTrace();
                }
            }
        });
     }
    
    //SEAT PLACE NUMBER
    
    public String seatPlace(){
          String[] arr={"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14","15",
              "16","17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28" , "29", "30", "31",
              "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46" , "47"
               };
         
      	Random r=new Random();        
      	int randomNumber=r.nextInt(arr.length);
        String text = String.valueOf(randomNumber);
        return text;
  
    }
    
    // LETTER FOR SEAT NUMBER
   public char seatPlaceLetter(){
        Random random = new Random();

        char randomizedCharacter = (char) (random.nextInt(5) + 'A');
        return randomizedCharacter;
   }
   
   // GATE NUMBER
     public String gateNumber(){
          String[] arr={"1", "2", "3", "4", "5", "6", "7", "8", "9"};
         
      	Random r=new Random();        
      	int randomNumber=r.nextInt(arr.length);
        String text = String.valueOf(randomNumber);
        return text;
  
    }
    //GATE LETTER
     public char gateLetter(){
        Random random = new Random();

        char randomizedCharacter = (char) (random.nextInt(3) + 'A');
        return randomizedCharacter;
   }
     
     // FLIGHT NUMBER 
    public String flightNumber(){
          String[] arr={"187", "265", "355", "444", "578", "976", "987", "0998", "988", "1076", "1651", "65512", "56413", "14645","15456",
              "145","157",  "8846" , "9847"};
         
      	Random r=new Random();        
      	int randomNumber=r.nextInt(arr.length);
        String text = String.valueOf(arr[randomNumber]);
        return text;
  
    }
    // FLIGHT LETTER 
      public char flightLetter(){
        Random random = new Random();

        char randomizedCharacter = (char) (random.nextInt(3) + 'A');
        return randomizedCharacter;
   }
    // RANDOM TIME HOURS 
        public String hours(){
          String[] arr={"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14","15",
              "16","17",  "18" , "19", "20", "21", "22", "23"};
         
      	Random r=new Random();        
      	int randomNumber=r.nextInt(arr.length);
        String text = String.valueOf(arr[randomNumber]);
        return text;
  
    }
        
        // RANDOM TIME MINUTES
           public String minutes(){
          String[] arr={"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14","15",
              "16","17",  "18" , "19", "20", "21", "22", "23", "24", "25", "26", "27","28", "29","30", 
              "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44","45",
              "46","47",  "48" , "49", "50", "51", "52", "53", "54", "55", "56", "57","58", "59"};
         
      	Random r=new Random();        
      	int randomNumber=r.nextInt(arr.length);
        String text = String.valueOf(arr[randomNumber]);
        return text;
  
    }
        
   
       //WRITING TO FILE
        
 
       
        public void writeToFile(String text){
            java.io.PrintWriter output = null;
            
            java.io.File file = new java.io.File("ticket.txt");
            
            try {
                output = new java.io.PrintWriter("ticket.txt");
                output.append(text);
                JOptionPane.showMessageDialog(rootPane, "Your confirmation code has been saved as a file!");
            } catch(java.io.IOException ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "operation is not successful!");
            }
            finally {
                if(output != null) output.close();
            }
        }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bookFlight;
    private javax.swing.JRadioButton businessBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JComboBox<String> dayReturnBox;
    private javax.swing.JRadioButton economyBtn;
    private javax.swing.JTextField fillFname;
    private javax.swing.JTextField fillLname;
    private javax.swing.JTextField fillPassportNumber;
    private javax.swing.JRadioButton firstclassBtn;
    private javax.swing.JComboBox<String> fromDestPicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JComboBox<String> monthReturnBox;
    private javax.swing.JRadioButton oneWayButton;
    private javax.swing.JButton priceButton;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JRadioButton roundTripButton;
    private javax.swing.JComboBox<String> toDestPicker;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JComboBox<String> yearReturnBox;
    // End of variables declaration//GEN-END:variables
}
