/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airplanesystem;

/**
 *
 * @author macbookair
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardinName = new javax.swing.JLabel();
        boardingFrom = new javax.swing.JLabel();
        flightNumbe = new javax.swing.JLabel();
        gateBoarding = new javax.swing.JLabel();
        toBoarding = new javax.swing.JLabel();
        dateBoarding = new javax.swing.JLabel();
        boardingTime = new javax.swing.JLabel();
        seatBoarding = new javax.swing.JLabel();
        boardinglastname = new javax.swing.JLabel();
        classBoarding = new javax.swing.JLabel();
        nameSide = new javax.swing.JLabel();
        LNameSide = new javax.swing.JLabel();
        fromSide = new javax.swing.JLabel();
        toSide = new javax.swing.JLabel();
        sideDate = new javax.swing.JLabel();
        flightNumberSide = new javax.swing.JLabel();
        seatSide = new javax.swing.JLabel();
        gateSide = new javax.swing.JLabel();
        boardingTimeSide = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(boardinName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 70, 20));
        getContentPane().add(boardingFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 90, 20));
        getContentPane().add(flightNumbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 110, 20));
        getContentPane().add(gateBoarding, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 70, 20));
        getContentPane().add(toBoarding, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 150, 20));
        getContentPane().add(dateBoarding, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, 20));
        getContentPane().add(boardingTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 90, 20));
        getContentPane().add(seatBoarding, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 80, 20));
        getContentPane().add(boardinglastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 90, 20));
        getContentPane().add(classBoarding, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 70, 20));
        getContentPane().add(nameSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 80, 20));
        getContentPane().add(LNameSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 70, 20));
        getContentPane().add(fromSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 90, 20));
        getContentPane().add(toSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 100, 20));
        getContentPane().add(sideDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 50, 20));
        getContentPane().add(flightNumberSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 50, 20));
        getContentPane().add(seatSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 60, 20));
        getContentPane().add(gateSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, 60, 20));
        getContentPane().add(boardingTimeSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 50, 20));

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airplanesystem/aaasdsadsadas.jpg"))); // NOI18N
        getContentPane().add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LNameSide;
    public static javax.swing.JLabel boardinName;
    public static javax.swing.JLabel boardingFrom;
    public static javax.swing.JLabel boardingTime;
    public static javax.swing.JLabel boardingTimeSide;
    public static javax.swing.JLabel boardinglastname;
    public static javax.swing.JLabel classBoarding;
    public static javax.swing.JLabel dateBoarding;
    public static javax.swing.JLabel flightNumbe;
    public static javax.swing.JLabel flightNumberSide;
    public static javax.swing.JLabel fromSide;
    public static javax.swing.JLabel gateBoarding;
    public static javax.swing.JLabel gateSide;
    private javax.swing.JLabel jlabel;
    public static javax.swing.JLabel nameSide;
    public static javax.swing.JLabel seatBoarding;
    public static javax.swing.JLabel seatSide;
    public static javax.swing.JLabel sideDate;
    public static javax.swing.JLabel toBoarding;
    protected static javax.swing.JLabel toSide;
    // End of variables declaration//GEN-END:variables
}
